// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: A1014Response.txt
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace DolphinServer.ProtoEntity {

  namespace Proto {

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class A1014Response {

      #region Extension registration
      public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
      }
      #endregion
      #region Static variables
      internal static pbd::MessageDescriptor internal__static_A1014Response__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::DolphinServer.ProtoEntity.A1014Response, global::DolphinServer.ProtoEntity.A1014Response.Builder> internal__static_A1014Response__FieldAccessorTable;
      #endregion
      #region Descriptor
      public static pbd::FileDescriptor Descriptor {
        get { return descriptor; }
      }
      private static pbd::FileDescriptor descriptor;

      static A1014Response() {
        byte[] descriptorData = global::System.Convert.FromBase64String(
            string.Concat(
              "ChFBMTAxNFJlc3BvbnNlLnR4dCKVAgoNQTEwMTRSZXNwb25zZRIRCglFcnJv", 
              "ckluZm8YASABKAkSEQoJRXJyb3JDb2RlGAIgASgFEgsKA1VpZBgDIAEoCRIO", 
              "CgZIdVR5cGUYBCABKAUSDQoFU2NvcmUYBSABKAUSEgoKVG90YWxTY29yZRgG", 
              "IAEoBRIOCgZEZXNVaWQYByABKAkSEAoIRGVzU2NvcmUYCCABKAUSDAoEQ2Fy", 
              "ZBgJIAEoBRINCgVDYXJkMRgKIAEoBRIVCg1EZXNUb3RhbFNjb3JlGAsgASgF", 
              "EhEKCU5pYW9DYXJkMRgMIAEoBRIRCglOaWFvQ2FyZDIYDSABKAUSEAoITmlh", 
              "b1VpZDEYDiABKAkSEAoITmlhb1VpZDIYDyABKAlCHKoCGURvbHBoaW5TZXJ2", 
            "ZXIuUHJvdG9FbnRpdHk="));
        pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
          descriptor = root;
          internal__static_A1014Response__Descriptor = Descriptor.MessageTypes[0];
          internal__static_A1014Response__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::DolphinServer.ProtoEntity.A1014Response, global::DolphinServer.ProtoEntity.A1014Response.Builder>(internal__static_A1014Response__Descriptor,
                  new string[] { "ErrorInfo", "ErrorCode", "Uid", "HuType", "Score", "TotalScore", "DesUid", "DesScore", "Card", "Card1", "DesTotalScore", "NiaoCard1", "NiaoCard2", "NiaoUid1", "NiaoUid2", });
          pb::ExtensionRegistry registry = pb::ExtensionRegistry.CreateInstance();
          RegisterAllExtensions(registry);
          return registry;
        };
        pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
            new pbd::FileDescriptor[] {
            }, assigner);
      }
      #endregion

    }
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class A1014Response : pb::GeneratedMessage<A1014Response, A1014Response.Builder> {
    private A1014Response() { }
    private static readonly A1014Response defaultInstance = new A1014Response().MakeReadOnly();
    private static readonly string[] _a1014ResponseFieldNames = new string[] { "Card", "Card1", "DesScore", "DesTotalScore", "DesUid", "ErrorCode", "ErrorInfo", "HuType", "NiaoCard1", "NiaoCard2", "NiaoUid1", "NiaoUid2", "Score", "TotalScore", "Uid" };
    private static readonly uint[] _a1014ResponseFieldTags = new uint[] { 72, 80, 64, 88, 58, 16, 10, 32, 96, 104, 114, 122, 40, 48, 26 };
    public static A1014Response DefaultInstance {
      get { return defaultInstance; }
    }

    public override A1014Response DefaultInstanceForType {
      get { return DefaultInstance; }
    }

    protected override A1014Response ThisMessage {
      get { return this; }
    }

    public static pbd::MessageDescriptor Descriptor {
      get { return global::DolphinServer.ProtoEntity.Proto.A1014Response.internal__static_A1014Response__Descriptor; }
    }

    protected override pb::FieldAccess.FieldAccessorTable<A1014Response, A1014Response.Builder> InternalFieldAccessors {
      get { return global::DolphinServer.ProtoEntity.Proto.A1014Response.internal__static_A1014Response__FieldAccessorTable; }
    }

    public const int ErrorInfoFieldNumber = 1;
    private bool hasErrorInfo;
    private string errorInfo_ = "";
    public bool HasErrorInfo {
      get { return hasErrorInfo; }
    }
    public string ErrorInfo {
      get { return errorInfo_; }
    }

    public const int ErrorCodeFieldNumber = 2;
    private bool hasErrorCode;
    private int errorCode_;
    public bool HasErrorCode {
      get { return hasErrorCode; }
    }
    public int ErrorCode {
      get { return errorCode_; }
    }

    public const int UidFieldNumber = 3;
    private bool hasUid;
    private string uid_ = "";
    public bool HasUid {
      get { return hasUid; }
    }
    public string Uid {
      get { return uid_; }
    }

    public const int HuTypeFieldNumber = 4;
    private bool hasHuType;
    private int huType_;
    public bool HasHuType {
      get { return hasHuType; }
    }
    public int HuType {
      get { return huType_; }
    }

    public const int ScoreFieldNumber = 5;
    private bool hasScore;
    private int score_;
    public bool HasScore {
      get { return hasScore; }
    }
    public int Score {
      get { return score_; }
    }

    public const int TotalScoreFieldNumber = 6;
    private bool hasTotalScore;
    private int totalScore_;
    public bool HasTotalScore {
      get { return hasTotalScore; }
    }
    public int TotalScore {
      get { return totalScore_; }
    }

    public const int DesUidFieldNumber = 7;
    private bool hasDesUid;
    private string desUid_ = "";
    public bool HasDesUid {
      get { return hasDesUid; }
    }
    public string DesUid {
      get { return desUid_; }
    }

    public const int DesScoreFieldNumber = 8;
    private bool hasDesScore;
    private int desScore_;
    public bool HasDesScore {
      get { return hasDesScore; }
    }
    public int DesScore {
      get { return desScore_; }
    }

    public const int CardFieldNumber = 9;
    private bool hasCard;
    private int card_;
    public bool HasCard {
      get { return hasCard; }
    }
    public int Card {
      get { return card_; }
    }

    public const int Card1FieldNumber = 10;
    private bool hasCard1;
    private int card1_;
    public bool HasCard1 {
      get { return hasCard1; }
    }
    public int Card1 {
      get { return card1_; }
    }

    public const int DesTotalScoreFieldNumber = 11;
    private bool hasDesTotalScore;
    private int desTotalScore_;
    public bool HasDesTotalScore {
      get { return hasDesTotalScore; }
    }
    public int DesTotalScore {
      get { return desTotalScore_; }
    }

    public const int NiaoCard1FieldNumber = 12;
    private bool hasNiaoCard1;
    private int niaoCard1_;
    public bool HasNiaoCard1 {
      get { return hasNiaoCard1; }
    }
    public int NiaoCard1 {
      get { return niaoCard1_; }
    }

    public const int NiaoCard2FieldNumber = 13;
    private bool hasNiaoCard2;
    private int niaoCard2_;
    public bool HasNiaoCard2 {
      get { return hasNiaoCard2; }
    }
    public int NiaoCard2 {
      get { return niaoCard2_; }
    }

    public const int NiaoUid1FieldNumber = 14;
    private bool hasNiaoUid1;
    private string niaoUid1_ = "";
    public bool HasNiaoUid1 {
      get { return hasNiaoUid1; }
    }
    public string NiaoUid1 {
      get { return niaoUid1_; }
    }

    public const int NiaoUid2FieldNumber = 15;
    private bool hasNiaoUid2;
    private string niaoUid2_ = "";
    public bool HasNiaoUid2 {
      get { return hasNiaoUid2; }
    }
    public string NiaoUid2 {
      get { return niaoUid2_; }
    }

    public override bool IsInitialized {
      get {
        return true;
      }
    }

    public override void WriteTo(pb::ICodedOutputStream output) {
      CalcSerializedSize();
      string[] field_names = _a1014ResponseFieldNames;
      if (hasErrorInfo) {
        output.WriteString(1, field_names[6], ErrorInfo);
      }
      if (hasErrorCode) {
        output.WriteInt32(2, field_names[5], ErrorCode);
      }
      if (hasUid) {
        output.WriteString(3, field_names[14], Uid);
      }
      if (hasHuType) {
        output.WriteInt32(4, field_names[7], HuType);
      }
      if (hasScore) {
        output.WriteInt32(5, field_names[12], Score);
      }
      if (hasTotalScore) {
        output.WriteInt32(6, field_names[13], TotalScore);
      }
      if (hasDesUid) {
        output.WriteString(7, field_names[4], DesUid);
      }
      if (hasDesScore) {
        output.WriteInt32(8, field_names[2], DesScore);
      }
      if (hasCard) {
        output.WriteInt32(9, field_names[0], Card);
      }
      if (hasCard1) {
        output.WriteInt32(10, field_names[1], Card1);
      }
      if (hasDesTotalScore) {
        output.WriteInt32(11, field_names[3], DesTotalScore);
      }
      if (hasNiaoCard1) {
        output.WriteInt32(12, field_names[8], NiaoCard1);
      }
      if (hasNiaoCard2) {
        output.WriteInt32(13, field_names[9], NiaoCard2);
      }
      if (hasNiaoUid1) {
        output.WriteString(14, field_names[10], NiaoUid1);
      }
      if (hasNiaoUid2) {
        output.WriteString(15, field_names[11], NiaoUid2);
      }
      UnknownFields.WriteTo(output);
    }

    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        return CalcSerializedSize();
      }
    }

    private int CalcSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (hasErrorInfo) {
        size += pb::CodedOutputStream.ComputeStringSize(1, ErrorInfo);
      }
      if (hasErrorCode) {
        size += pb::CodedOutputStream.ComputeInt32Size(2, ErrorCode);
      }
      if (hasUid) {
        size += pb::CodedOutputStream.ComputeStringSize(3, Uid);
      }
      if (hasHuType) {
        size += pb::CodedOutputStream.ComputeInt32Size(4, HuType);
      }
      if (hasScore) {
        size += pb::CodedOutputStream.ComputeInt32Size(5, Score);
      }
      if (hasTotalScore) {
        size += pb::CodedOutputStream.ComputeInt32Size(6, TotalScore);
      }
      if (hasDesUid) {
        size += pb::CodedOutputStream.ComputeStringSize(7, DesUid);
      }
      if (hasDesScore) {
        size += pb::CodedOutputStream.ComputeInt32Size(8, DesScore);
      }
      if (hasCard) {
        size += pb::CodedOutputStream.ComputeInt32Size(9, Card);
      }
      if (hasCard1) {
        size += pb::CodedOutputStream.ComputeInt32Size(10, Card1);
      }
      if (hasDesTotalScore) {
        size += pb::CodedOutputStream.ComputeInt32Size(11, DesTotalScore);
      }
      if (hasNiaoCard1) {
        size += pb::CodedOutputStream.ComputeInt32Size(12, NiaoCard1);
      }
      if (hasNiaoCard2) {
        size += pb::CodedOutputStream.ComputeInt32Size(13, NiaoCard2);
      }
      if (hasNiaoUid1) {
        size += pb::CodedOutputStream.ComputeStringSize(14, NiaoUid1);
      }
      if (hasNiaoUid2) {
        size += pb::CodedOutputStream.ComputeStringSize(15, NiaoUid2);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
    public static A1014Response ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static A1014Response ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static A1014Response ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static A1014Response ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static A1014Response ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static A1014Response ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static A1014Response ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static A1014Response ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static A1014Response ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static A1014Response ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private A1014Response MakeReadOnly() {
      return this;
    }

    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(A1014Response prototype) {
      return new Builder(prototype);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<A1014Response, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(A1014Response cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }

      private bool resultIsReadOnly;
      private A1014Response result;

      private A1014Response PrepareBuilder() {
        if (resultIsReadOnly) {
          A1014Response original = result;
          result = new A1014Response();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }

      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }

      protected override A1014Response MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }

      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }

      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }

      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::DolphinServer.ProtoEntity.A1014Response.Descriptor; }
      }

      public override A1014Response DefaultInstanceForType {
        get { return global::DolphinServer.ProtoEntity.A1014Response.DefaultInstance; }
      }

      public override A1014Response BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }

      public override Builder MergeFrom(pb::IMessage other) {
        if (other is A1014Response) {
          return MergeFrom((A1014Response) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }

      public override Builder MergeFrom(A1014Response other) {
        if (other == global::DolphinServer.ProtoEntity.A1014Response.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasErrorInfo) {
          ErrorInfo = other.ErrorInfo;
        }
        if (other.HasErrorCode) {
          ErrorCode = other.ErrorCode;
        }
        if (other.HasUid) {
          Uid = other.Uid;
        }
        if (other.HasHuType) {
          HuType = other.HuType;
        }
        if (other.HasScore) {
          Score = other.Score;
        }
        if (other.HasTotalScore) {
          TotalScore = other.TotalScore;
        }
        if (other.HasDesUid) {
          DesUid = other.DesUid;
        }
        if (other.HasDesScore) {
          DesScore = other.DesScore;
        }
        if (other.HasCard) {
          Card = other.Card;
        }
        if (other.HasCard1) {
          Card1 = other.Card1;
        }
        if (other.HasDesTotalScore) {
          DesTotalScore = other.DesTotalScore;
        }
        if (other.HasNiaoCard1) {
          NiaoCard1 = other.NiaoCard1;
        }
        if (other.HasNiaoCard2) {
          NiaoCard2 = other.NiaoCard2;
        }
        if (other.HasNiaoUid1) {
          NiaoUid1 = other.NiaoUid1;
        }
        if (other.HasNiaoUid2) {
          NiaoUid2 = other.NiaoUid2;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }

      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }

      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_a1014ResponseFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _a1014ResponseFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              result.hasErrorInfo = input.ReadString(ref result.errorInfo_);
              break;
            }
            case 16: {
              result.hasErrorCode = input.ReadInt32(ref result.errorCode_);
              break;
            }
            case 26: {
              result.hasUid = input.ReadString(ref result.uid_);
              break;
            }
            case 32: {
              result.hasHuType = input.ReadInt32(ref result.huType_);
              break;
            }
            case 40: {
              result.hasScore = input.ReadInt32(ref result.score_);
              break;
            }
            case 48: {
              result.hasTotalScore = input.ReadInt32(ref result.totalScore_);
              break;
            }
            case 58: {
              result.hasDesUid = input.ReadString(ref result.desUid_);
              break;
            }
            case 64: {
              result.hasDesScore = input.ReadInt32(ref result.desScore_);
              break;
            }
            case 72: {
              result.hasCard = input.ReadInt32(ref result.card_);
              break;
            }
            case 80: {
              result.hasCard1 = input.ReadInt32(ref result.card1_);
              break;
            }
            case 88: {
              result.hasDesTotalScore = input.ReadInt32(ref result.desTotalScore_);
              break;
            }
            case 96: {
              result.hasNiaoCard1 = input.ReadInt32(ref result.niaoCard1_);
              break;
            }
            case 104: {
              result.hasNiaoCard2 = input.ReadInt32(ref result.niaoCard2_);
              break;
            }
            case 114: {
              result.hasNiaoUid1 = input.ReadString(ref result.niaoUid1_);
              break;
            }
            case 122: {
              result.hasNiaoUid2 = input.ReadString(ref result.niaoUid2_);
              break;
            }
          }
        }

        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }


      public bool HasErrorInfo {
        get { return result.hasErrorInfo; }
      }
      public string ErrorInfo {
        get { return result.ErrorInfo; }
        set { SetErrorInfo(value); }
      }
      public Builder SetErrorInfo(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasErrorInfo = true;
        result.errorInfo_ = value;
        return this;
      }
      public Builder ClearErrorInfo() {
        PrepareBuilder();
        result.hasErrorInfo = false;
        result.errorInfo_ = "";
        return this;
      }

      public bool HasErrorCode {
        get { return result.hasErrorCode; }
      }
      public int ErrorCode {
        get { return result.ErrorCode; }
        set { SetErrorCode(value); }
      }
      public Builder SetErrorCode(int value) {
        PrepareBuilder();
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder ClearErrorCode() {
        PrepareBuilder();
        result.hasErrorCode = false;
        result.errorCode_ = 0;
        return this;
      }

      public bool HasUid {
        get { return result.hasUid; }
      }
      public string Uid {
        get { return result.Uid; }
        set { SetUid(value); }
      }
      public Builder SetUid(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasUid = true;
        result.uid_ = value;
        return this;
      }
      public Builder ClearUid() {
        PrepareBuilder();
        result.hasUid = false;
        result.uid_ = "";
        return this;
      }

      public bool HasHuType {
        get { return result.hasHuType; }
      }
      public int HuType {
        get { return result.HuType; }
        set { SetHuType(value); }
      }
      public Builder SetHuType(int value) {
        PrepareBuilder();
        result.hasHuType = true;
        result.huType_ = value;
        return this;
      }
      public Builder ClearHuType() {
        PrepareBuilder();
        result.hasHuType = false;
        result.huType_ = 0;
        return this;
      }

      public bool HasScore {
        get { return result.hasScore; }
      }
      public int Score {
        get { return result.Score; }
        set { SetScore(value); }
      }
      public Builder SetScore(int value) {
        PrepareBuilder();
        result.hasScore = true;
        result.score_ = value;
        return this;
      }
      public Builder ClearScore() {
        PrepareBuilder();
        result.hasScore = false;
        result.score_ = 0;
        return this;
      }

      public bool HasTotalScore {
        get { return result.hasTotalScore; }
      }
      public int TotalScore {
        get { return result.TotalScore; }
        set { SetTotalScore(value); }
      }
      public Builder SetTotalScore(int value) {
        PrepareBuilder();
        result.hasTotalScore = true;
        result.totalScore_ = value;
        return this;
      }
      public Builder ClearTotalScore() {
        PrepareBuilder();
        result.hasTotalScore = false;
        result.totalScore_ = 0;
        return this;
      }

      public bool HasDesUid {
        get { return result.hasDesUid; }
      }
      public string DesUid {
        get { return result.DesUid; }
        set { SetDesUid(value); }
      }
      public Builder SetDesUid(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasDesUid = true;
        result.desUid_ = value;
        return this;
      }
      public Builder ClearDesUid() {
        PrepareBuilder();
        result.hasDesUid = false;
        result.desUid_ = "";
        return this;
      }

      public bool HasDesScore {
        get { return result.hasDesScore; }
      }
      public int DesScore {
        get { return result.DesScore; }
        set { SetDesScore(value); }
      }
      public Builder SetDesScore(int value) {
        PrepareBuilder();
        result.hasDesScore = true;
        result.desScore_ = value;
        return this;
      }
      public Builder ClearDesScore() {
        PrepareBuilder();
        result.hasDesScore = false;
        result.desScore_ = 0;
        return this;
      }

      public bool HasCard {
        get { return result.hasCard; }
      }
      public int Card {
        get { return result.Card; }
        set { SetCard(value); }
      }
      public Builder SetCard(int value) {
        PrepareBuilder();
        result.hasCard = true;
        result.card_ = value;
        return this;
      }
      public Builder ClearCard() {
        PrepareBuilder();
        result.hasCard = false;
        result.card_ = 0;
        return this;
      }

      public bool HasCard1 {
        get { return result.hasCard1; }
      }
      public int Card1 {
        get { return result.Card1; }
        set { SetCard1(value); }
      }
      public Builder SetCard1(int value) {
        PrepareBuilder();
        result.hasCard1 = true;
        result.card1_ = value;
        return this;
      }
      public Builder ClearCard1() {
        PrepareBuilder();
        result.hasCard1 = false;
        result.card1_ = 0;
        return this;
      }

      public bool HasDesTotalScore {
        get { return result.hasDesTotalScore; }
      }
      public int DesTotalScore {
        get { return result.DesTotalScore; }
        set { SetDesTotalScore(value); }
      }
      public Builder SetDesTotalScore(int value) {
        PrepareBuilder();
        result.hasDesTotalScore = true;
        result.desTotalScore_ = value;
        return this;
      }
      public Builder ClearDesTotalScore() {
        PrepareBuilder();
        result.hasDesTotalScore = false;
        result.desTotalScore_ = 0;
        return this;
      }

      public bool HasNiaoCard1 {
        get { return result.hasNiaoCard1; }
      }
      public int NiaoCard1 {
        get { return result.NiaoCard1; }
        set { SetNiaoCard1(value); }
      }
      public Builder SetNiaoCard1(int value) {
        PrepareBuilder();
        result.hasNiaoCard1 = true;
        result.niaoCard1_ = value;
        return this;
      }
      public Builder ClearNiaoCard1() {
        PrepareBuilder();
        result.hasNiaoCard1 = false;
        result.niaoCard1_ = 0;
        return this;
      }

      public bool HasNiaoCard2 {
        get { return result.hasNiaoCard2; }
      }
      public int NiaoCard2 {
        get { return result.NiaoCard2; }
        set { SetNiaoCard2(value); }
      }
      public Builder SetNiaoCard2(int value) {
        PrepareBuilder();
        result.hasNiaoCard2 = true;
        result.niaoCard2_ = value;
        return this;
      }
      public Builder ClearNiaoCard2() {
        PrepareBuilder();
        result.hasNiaoCard2 = false;
        result.niaoCard2_ = 0;
        return this;
      }

      public bool HasNiaoUid1 {
        get { return result.hasNiaoUid1; }
      }
      public string NiaoUid1 {
        get { return result.NiaoUid1; }
        set { SetNiaoUid1(value); }
      }
      public Builder SetNiaoUid1(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasNiaoUid1 = true;
        result.niaoUid1_ = value;
        return this;
      }
      public Builder ClearNiaoUid1() {
        PrepareBuilder();
        result.hasNiaoUid1 = false;
        result.niaoUid1_ = "";
        return this;
      }

      public bool HasNiaoUid2 {
        get { return result.hasNiaoUid2; }
      }
      public string NiaoUid2 {
        get { return result.NiaoUid2; }
        set { SetNiaoUid2(value); }
      }
      public Builder SetNiaoUid2(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasNiaoUid2 = true;
        result.niaoUid2_ = value;
        return this;
      }
      public Builder ClearNiaoUid2() {
        PrepareBuilder();
        result.hasNiaoUid2 = false;
        result.niaoUid2_ = "";
        return this;
      }
    }
    static A1014Response() {
      object.ReferenceEquals(global::DolphinServer.ProtoEntity.Proto.A1014Response.Descriptor, null);
    }
  }

  #endregion

}

#endregion Designer generated code
