// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: A1026Response.txt
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace DolphinServer.ProtoEntity {

  namespace Proto {

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class A1026Response {

      #region Extension registration
      public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
      }
      #endregion
      #region Static variables
      internal static pbd::MessageDescriptor internal__static_A1026Response__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::DolphinServer.ProtoEntity.A1026Response, global::DolphinServer.ProtoEntity.A1026Response.Builder> internal__static_A1026Response__FieldAccessorTable;
      internal static pbd::MessageDescriptor internal__static_A1026GameResult__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::DolphinServer.ProtoEntity.A1026GameResult, global::DolphinServer.ProtoEntity.A1026GameResult.Builder> internal__static_A1026GameResult__FieldAccessorTable;
      #endregion
      #region Descriptor
      public static pbd::FileDescriptor Descriptor {
        get { return descriptor; }
      }
      private static pbd::FileDescriptor descriptor;

      static A1026Response() {
        byte[] descriptorData = global::System.Convert.FromBase64String(
            string.Concat(
              "ChFBMTAyNlJlc3BvbnNlLnR4dCJYCg1BMTAyNlJlc3BvbnNlEhEKCUVycm9y", 
              "SW5mbxgBIAEoCRIRCglFcnJvckNvZGUYAiABKAUSIQoHR1Jlc3VsdBgDIAMo", 
              "CzIQLkExMDI2R2FtZVJlc3VsdCJKCg9BMTAyNkdhbWVSZXN1bHQSFgoOUmVz", 
              "dWx0QWN0aW9uSWQYASABKAkSDQoFU2NvcmUYAiABKAUSEAoIRGF0ZVRpbWUY", 
            "AyABKAlCHKoCGURvbHBoaW5TZXJ2ZXIuUHJvdG9FbnRpdHk="));
        pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
          descriptor = root;
          internal__static_A1026Response__Descriptor = Descriptor.MessageTypes[0];
          internal__static_A1026Response__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::DolphinServer.ProtoEntity.A1026Response, global::DolphinServer.ProtoEntity.A1026Response.Builder>(internal__static_A1026Response__Descriptor,
                  new string[] { "ErrorInfo", "ErrorCode", "GResult", });
          internal__static_A1026GameResult__Descriptor = Descriptor.MessageTypes[1];
          internal__static_A1026GameResult__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::DolphinServer.ProtoEntity.A1026GameResult, global::DolphinServer.ProtoEntity.A1026GameResult.Builder>(internal__static_A1026GameResult__Descriptor,
                  new string[] { "ResultActionId", "Score", "DateTime", });
          pb::ExtensionRegistry registry = pb::ExtensionRegistry.CreateInstance();
          RegisterAllExtensions(registry);
          return registry;
        };
        pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
            new pbd::FileDescriptor[] {
            }, assigner);
      }
      #endregion

    }
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class A1026Response : pb::GeneratedMessage<A1026Response, A1026Response.Builder> {
    private A1026Response() { }
    private static readonly A1026Response defaultInstance = new A1026Response().MakeReadOnly();
    private static readonly string[] _a1026ResponseFieldNames = new string[] { "ErrorCode", "ErrorInfo", "GResult" };
    private static readonly uint[] _a1026ResponseFieldTags = new uint[] { 16, 10, 26 };
    public static A1026Response DefaultInstance {
      get { return defaultInstance; }
    }

    public override A1026Response DefaultInstanceForType {
      get { return DefaultInstance; }
    }

    protected override A1026Response ThisMessage {
      get { return this; }
    }

    public static pbd::MessageDescriptor Descriptor {
      get { return global::DolphinServer.ProtoEntity.Proto.A1026Response.internal__static_A1026Response__Descriptor; }
    }

    protected override pb::FieldAccess.FieldAccessorTable<A1026Response, A1026Response.Builder> InternalFieldAccessors {
      get { return global::DolphinServer.ProtoEntity.Proto.A1026Response.internal__static_A1026Response__FieldAccessorTable; }
    }

    public const int ErrorInfoFieldNumber = 1;
    private bool hasErrorInfo;
    private string errorInfo_ = "";
    public bool HasErrorInfo {
      get { return hasErrorInfo; }
    }
    public string ErrorInfo {
      get { return errorInfo_; }
    }

    public const int ErrorCodeFieldNumber = 2;
    private bool hasErrorCode;
    private int errorCode_;
    public bool HasErrorCode {
      get { return hasErrorCode; }
    }
    public int ErrorCode {
      get { return errorCode_; }
    }

    public const int GResultFieldNumber = 3;
    private pbc::PopsicleList<global::DolphinServer.ProtoEntity.A1026GameResult> gResult_ = new pbc::PopsicleList<global::DolphinServer.ProtoEntity.A1026GameResult>();
    public scg::IList<global::DolphinServer.ProtoEntity.A1026GameResult> GResultList {
      get { return gResult_; }
    }
    public int GResultCount {
      get { return gResult_.Count; }
    }
    public global::DolphinServer.ProtoEntity.A1026GameResult GetGResult(int index) {
      return gResult_[index];
    }

    public override bool IsInitialized {
      get {
        return true;
      }
    }

    public override void WriteTo(pb::ICodedOutputStream output) {
      CalcSerializedSize();
      string[] field_names = _a1026ResponseFieldNames;
      if (hasErrorInfo) {
        output.WriteString(1, field_names[1], ErrorInfo);
      }
      if (hasErrorCode) {
        output.WriteInt32(2, field_names[0], ErrorCode);
      }
      if (gResult_.Count > 0) {
        output.WriteMessageArray(3, field_names[2], gResult_);
      }
      UnknownFields.WriteTo(output);
    }

    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        return CalcSerializedSize();
      }
    }

    private int CalcSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (hasErrorInfo) {
        size += pb::CodedOutputStream.ComputeStringSize(1, ErrorInfo);
      }
      if (hasErrorCode) {
        size += pb::CodedOutputStream.ComputeInt32Size(2, ErrorCode);
      }
      foreach (global::DolphinServer.ProtoEntity.A1026GameResult element in GResultList) {
        size += pb::CodedOutputStream.ComputeMessageSize(3, element);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
    public static A1026Response ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static A1026Response ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static A1026Response ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static A1026Response ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static A1026Response ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static A1026Response ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static A1026Response ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static A1026Response ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static A1026Response ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static A1026Response ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private A1026Response MakeReadOnly() {
      gResult_.MakeReadOnly();
      return this;
    }

    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(A1026Response prototype) {
      return new Builder(prototype);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<A1026Response, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(A1026Response cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }

      private bool resultIsReadOnly;
      private A1026Response result;

      private A1026Response PrepareBuilder() {
        if (resultIsReadOnly) {
          A1026Response original = result;
          result = new A1026Response();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }

      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }

      protected override A1026Response MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }

      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }

      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }

      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::DolphinServer.ProtoEntity.A1026Response.Descriptor; }
      }

      public override A1026Response DefaultInstanceForType {
        get { return global::DolphinServer.ProtoEntity.A1026Response.DefaultInstance; }
      }

      public override A1026Response BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }

      public override Builder MergeFrom(pb::IMessage other) {
        if (other is A1026Response) {
          return MergeFrom((A1026Response) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }

      public override Builder MergeFrom(A1026Response other) {
        if (other == global::DolphinServer.ProtoEntity.A1026Response.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasErrorInfo) {
          ErrorInfo = other.ErrorInfo;
        }
        if (other.HasErrorCode) {
          ErrorCode = other.ErrorCode;
        }
        if (other.gResult_.Count != 0) {
          result.gResult_.Add(other.gResult_);
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }

      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }

      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_a1026ResponseFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _a1026ResponseFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              result.hasErrorInfo = input.ReadString(ref result.errorInfo_);
              break;
            }
            case 16: {
              result.hasErrorCode = input.ReadInt32(ref result.errorCode_);
              break;
            }
            case 26: {
              input.ReadMessageArray(tag, field_name, result.gResult_, global::DolphinServer.ProtoEntity.A1026GameResult.DefaultInstance, extensionRegistry);
              break;
            }
          }
        }

        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }


      public bool HasErrorInfo {
        get { return result.hasErrorInfo; }
      }
      public string ErrorInfo {
        get { return result.ErrorInfo; }
        set { SetErrorInfo(value); }
      }
      public Builder SetErrorInfo(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasErrorInfo = true;
        result.errorInfo_ = value;
        return this;
      }
      public Builder ClearErrorInfo() {
        PrepareBuilder();
        result.hasErrorInfo = false;
        result.errorInfo_ = "";
        return this;
      }

      public bool HasErrorCode {
        get { return result.hasErrorCode; }
      }
      public int ErrorCode {
        get { return result.ErrorCode; }
        set { SetErrorCode(value); }
      }
      public Builder SetErrorCode(int value) {
        PrepareBuilder();
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder ClearErrorCode() {
        PrepareBuilder();
        result.hasErrorCode = false;
        result.errorCode_ = 0;
        return this;
      }

      public pbc::IPopsicleList<global::DolphinServer.ProtoEntity.A1026GameResult> GResultList {
        get { return PrepareBuilder().gResult_; }
      }
      public int GResultCount {
        get { return result.GResultCount; }
      }
      public global::DolphinServer.ProtoEntity.A1026GameResult GetGResult(int index) {
        return result.GetGResult(index);
      }
      public Builder SetGResult(int index, global::DolphinServer.ProtoEntity.A1026GameResult value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.gResult_[index] = value;
        return this;
      }
      public Builder SetGResult(int index, global::DolphinServer.ProtoEntity.A1026GameResult.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.gResult_[index] = builderForValue.Build();
        return this;
      }
      public Builder AddGResult(global::DolphinServer.ProtoEntity.A1026GameResult value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.gResult_.Add(value);
        return this;
      }
      public Builder AddGResult(global::DolphinServer.ProtoEntity.A1026GameResult.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.gResult_.Add(builderForValue.Build());
        return this;
      }
      public Builder AddRangeGResult(scg::IEnumerable<global::DolphinServer.ProtoEntity.A1026GameResult> values) {
        PrepareBuilder();
        result.gResult_.Add(values);
        return this;
      }
      public Builder ClearGResult() {
        PrepareBuilder();
        result.gResult_.Clear();
        return this;
      }
    }
    static A1026Response() {
      object.ReferenceEquals(global::DolphinServer.ProtoEntity.Proto.A1026Response.Descriptor, null);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class A1026GameResult : pb::GeneratedMessage<A1026GameResult, A1026GameResult.Builder> {
    private A1026GameResult() { }
    private static readonly A1026GameResult defaultInstance = new A1026GameResult().MakeReadOnly();
    private static readonly string[] _a1026GameResultFieldNames = new string[] { "DateTime", "ResultActionId", "Score" };
    private static readonly uint[] _a1026GameResultFieldTags = new uint[] { 26, 10, 16 };
    public static A1026GameResult DefaultInstance {
      get { return defaultInstance; }
    }

    public override A1026GameResult DefaultInstanceForType {
      get { return DefaultInstance; }
    }

    protected override A1026GameResult ThisMessage {
      get { return this; }
    }

    public static pbd::MessageDescriptor Descriptor {
      get { return global::DolphinServer.ProtoEntity.Proto.A1026Response.internal__static_A1026GameResult__Descriptor; }
    }

    protected override pb::FieldAccess.FieldAccessorTable<A1026GameResult, A1026GameResult.Builder> InternalFieldAccessors {
      get { return global::DolphinServer.ProtoEntity.Proto.A1026Response.internal__static_A1026GameResult__FieldAccessorTable; }
    }

    public const int ResultActionIdFieldNumber = 1;
    private bool hasResultActionId;
    private string resultActionId_ = "";
    public bool HasResultActionId {
      get { return hasResultActionId; }
    }
    public string ResultActionId {
      get { return resultActionId_; }
    }

    public const int ScoreFieldNumber = 2;
    private bool hasScore;
    private int score_;
    public bool HasScore {
      get { return hasScore; }
    }
    public int Score {
      get { return score_; }
    }

    public const int DateTimeFieldNumber = 3;
    private bool hasDateTime;
    private string dateTime_ = "";
    public bool HasDateTime {
      get { return hasDateTime; }
    }
    public string DateTime {
      get { return dateTime_; }
    }

    public override bool IsInitialized {
      get {
        return true;
      }
    }

    public override void WriteTo(pb::ICodedOutputStream output) {
      CalcSerializedSize();
      string[] field_names = _a1026GameResultFieldNames;
      if (hasResultActionId) {
        output.WriteString(1, field_names[1], ResultActionId);
      }
      if (hasScore) {
        output.WriteInt32(2, field_names[2], Score);
      }
      if (hasDateTime) {
        output.WriteString(3, field_names[0], DateTime);
      }
      UnknownFields.WriteTo(output);
    }

    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        return CalcSerializedSize();
      }
    }

    private int CalcSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (hasResultActionId) {
        size += pb::CodedOutputStream.ComputeStringSize(1, ResultActionId);
      }
      if (hasScore) {
        size += pb::CodedOutputStream.ComputeInt32Size(2, Score);
      }
      if (hasDateTime) {
        size += pb::CodedOutputStream.ComputeStringSize(3, DateTime);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
    public static A1026GameResult ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static A1026GameResult ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static A1026GameResult ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static A1026GameResult ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static A1026GameResult ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static A1026GameResult ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static A1026GameResult ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static A1026GameResult ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static A1026GameResult ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static A1026GameResult ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private A1026GameResult MakeReadOnly() {
      return this;
    }

    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(A1026GameResult prototype) {
      return new Builder(prototype);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<A1026GameResult, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(A1026GameResult cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }

      private bool resultIsReadOnly;
      private A1026GameResult result;

      private A1026GameResult PrepareBuilder() {
        if (resultIsReadOnly) {
          A1026GameResult original = result;
          result = new A1026GameResult();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }

      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }

      protected override A1026GameResult MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }

      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }

      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }

      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::DolphinServer.ProtoEntity.A1026GameResult.Descriptor; }
      }

      public override A1026GameResult DefaultInstanceForType {
        get { return global::DolphinServer.ProtoEntity.A1026GameResult.DefaultInstance; }
      }

      public override A1026GameResult BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }

      public override Builder MergeFrom(pb::IMessage other) {
        if (other is A1026GameResult) {
          return MergeFrom((A1026GameResult) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }

      public override Builder MergeFrom(A1026GameResult other) {
        if (other == global::DolphinServer.ProtoEntity.A1026GameResult.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasResultActionId) {
          ResultActionId = other.ResultActionId;
        }
        if (other.HasScore) {
          Score = other.Score;
        }
        if (other.HasDateTime) {
          DateTime = other.DateTime;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }

      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }

      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_a1026GameResultFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _a1026GameResultFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              result.hasResultActionId = input.ReadString(ref result.resultActionId_);
              break;
            }
            case 16: {
              result.hasScore = input.ReadInt32(ref result.score_);
              break;
            }
            case 26: {
              result.hasDateTime = input.ReadString(ref result.dateTime_);
              break;
            }
          }
        }

        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }


      public bool HasResultActionId {
        get { return result.hasResultActionId; }
      }
      public string ResultActionId {
        get { return result.ResultActionId; }
        set { SetResultActionId(value); }
      }
      public Builder SetResultActionId(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasResultActionId = true;
        result.resultActionId_ = value;
        return this;
      }
      public Builder ClearResultActionId() {
        PrepareBuilder();
        result.hasResultActionId = false;
        result.resultActionId_ = "";
        return this;
      }

      public bool HasScore {
        get { return result.hasScore; }
      }
      public int Score {
        get { return result.Score; }
        set { SetScore(value); }
      }
      public Builder SetScore(int value) {
        PrepareBuilder();
        result.hasScore = true;
        result.score_ = value;
        return this;
      }
      public Builder ClearScore() {
        PrepareBuilder();
        result.hasScore = false;
        result.score_ = 0;
        return this;
      }

      public bool HasDateTime {
        get { return result.hasDateTime; }
      }
      public string DateTime {
        get { return result.DateTime; }
        set { SetDateTime(value); }
      }
      public Builder SetDateTime(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasDateTime = true;
        result.dateTime_ = value;
        return this;
      }
      public Builder ClearDateTime() {
        PrepareBuilder();
        result.hasDateTime = false;
        result.dateTime_ = "";
        return this;
      }
    }
    static A1026GameResult() {
      object.ReferenceEquals(global::DolphinServer.ProtoEntity.Proto.A1026Response.Descriptor, null);
    }
  }

  #endregion

}

#endregion Designer generated code
